create or replace NONEDITIONABLE PACKAGE BODY PCKG_MIG_COMPARE_LIEN AS
/******************************************************************************
   NAME:       PCKG_MIG_COMPARE_USER
   PURPOSE: migration user 1 Processing

   REVISIONS:
   Ver        Date        Author           Description
   ---------  ----------  ---------------  ------------------------------------
   1.0        04/03/2025   dedywadenk          1. Created this package.
******************************************************************************/
PROCEDURE process_MIG_COMPARE (KEY IN VARCHAR) AS
  BEGIN
    ava_MST_LIEN_PRICE_TIERS(sysdate);
    ava_MST_LIEN_PRICE_STRUCTURES(sysdate);
    ava_TRX_LIEN_PRODUCTS(sysdate);
    ava_TRX_LIEN_TRANSACTION(sysdate);
    commit;
  END process_MIG_COMPARE;

    PROCEDURE process_COMPARE_TABLE(table_source IN VARCHAR2, col_source IN VARCHAR2, table_dest IN VARCHAR2, col_dest IN VARCHAR2,start_date TIMESTAMP, Key_Group IN VARCHAR2)  AS 
    v_string_1  VARCHAR2(32767);
    v_table_temp  VARCHAR2(32767);
    v_sql_string  VARCHAR2(32767);
    v_count_table  VARCHAR2(1000);
    key_number number:=0;
    BEGIN

    --v_string_1:='temp_'||substr(table_dest,11,length(_dest));
    if UPPER(substr(table_dest,0,10))='AVANTRADE.' then
    v_string_1:='temp_'||substr(table_dest,11,length(table_dest));
    else if  UPPER(substr(table_dest,0,7))='ENTITY.' then
        v_string_1:='temp_'||substr(table_dest,8,length(table_dest));        
        end if;
    end if;
    drop_table(v_string_1) ;

    v_table_temp:='create table '|| v_string_1 || ' as select 1 src1,1 src2,'|| col_dest ||' from ' || table_dest || ' WHERE 1=2';
    EXECUTE IMMEDIATE v_table_temp;     
    IF Key_Group='' THEN
    v_sql_string:='INSERT INTO '|| v_string_1 || ' SELECT * ' ||  
         ' FROM (SELECT COUNT(src1) CNT1,COUNT(src2) CNT2,'|| col_dest ||' FROM(SELECT  1 src1 , TO_NUMBER(NULL) src2,' ||
         col_source || ' FROM ' || table_source || 
         ' UNION ALL  SELECT  TO_NUMBER(NULL) src1, 2 src2,' ||  col_dest || 
         ' FROM ' || table_dest || ') GROUP BY ' || col_dest ||
         ' HAVING COUNT(src1) <> COUNT(src2))' ;
    ELSE
    v_sql_string:='INSERT INTO '|| v_string_1 || ' SELECT * ' ||  
         ' FROM (SELECT COUNT(src1) CNT1,COUNT(src2) CNT2,'|| col_dest ||' FROM(SELECT  1 src1 , TO_NUMBER(NULL) src2,' ||
         col_source || ' FROM ' || table_source || Key_Group ||
         ' UNION ALL  SELECT  TO_NUMBER(NULL) src1, 2 src2,' ||  col_source || 
         ' FROM ' || table_dest || Key_Group || ') GROUP BY ' || col_dest ||
         ' HAVING COUNT(src1) <> COUNT(src2))' ;
    END IF;
    EXECUTE IMMEDIATE v_sql_string;
    v_count_table:='select count(*) from ' || v_string_1;
    EXECUTE IMMEDIATE v_count_table into key_number;

    if key_number>0 then
    LOG_COMPARE_DATA (v_string_1,table_source,table_dest,'select  * from ' || v_string_1,start_date,cast(sysdate as timestamp));    
     commit;
    PCKG_MIG_COMPARE_DETAIL.P_COMPARE_TABLE_DETAIL(v_string_1, table_source,table_dest) ;    
     commit;
    else
    LOG_COMPARE_DATA ('SUCCESS',table_source,table_dest,'VALID',start_date,cast(sysdate as timestamp));
     drop_table(v_string_1) ;     
     commit;
    end if;
    END process_COMPARE_TABLE;

    PROCEDURE LOG_COMPARE_DATA(KEY_TABLE IN VARCHAR2, SOURCE_TABLE IN VARCHAR2, DESTINATION_TABLE IN VARCHAR2, COL_VALUE IN VARCHAR2, START_DATE IN timestamp, END_DATE IN timestamp) AS
    BEGIN
    INSERT INTO LOG_COMPARE_DATA VALUES (KEY_TABLE,SOURCE_TABLE,DESTINATION_TABLE,COL_VALUE,start_date,END_DATE);
    END;

    FUNCTION column_exists (table_name IN VARCHAR2,col_name IN VARCHAR2) RETURN PLS_INTEGER
    AS
       sql_query VARCHAR2 (200) := 'SELECT COUNT(*) FROM ' || table_name;
       ret_val PLS_INTEGER ;
    BEGIN
       EXECUTE IMMEDIATE sql_query INTO ret_val;
       RETURN ret_val;
    END;  

    function split_string( p_string VARCHAR2, p_delimiter VARCHAR2 )  RETURN SYS.ODCIVARCHAR2LIST
        PIPELINED IS
            v_start_index NUMBER := 1;
            v_end_index NUMBER;
        BEGIN
            WHILE v_start_index <= LENGTH(p_string) LOOP
                v_end_index := INSTR(p_string, p_delimiter, v_start_index);
                IF v_end_index = 0 THEN
                    PIPE ROW (SUBSTR(p_string, v_start_index));
                    RETURN;
                END IF;

                PIPE ROW (SUBSTR(p_string, v_start_index, v_end_index - v_start_index));
                v_start_index := trim(v_end_index) + 1;
            END LOOP;
        END split_string;

    procedure drop_table  (table_name IN VARCHAR2) AS
    sql_query VARCHAR2 (200) := 'DROP TABLE ' || table_name;
    BEGIN 
    EXECUTE IMMEDIATE sql_query;
    EXCEPTION WHEN OTHERS THEN NULL; 
    END;

   procedure trunc_table (table_name IN VARCHAR2) AS
       sql_query VARCHAR2 (200) := 'TRUNCATE TABLE ' || table_name;
    BEGIN
       EXECUTE IMMEDIATE sql_query;
    END;  

PROCEDURE ava_MST_LIEN_PRICE_TIERS(start_date TIMESTAMP) AS
BEGIN
process_COMPARE_TABLE(
    'MST_LIEN_PRICE_TIERS@DBLINK_AVANTRADE'
    ,'PRICE_TIER_ID, PRICE_ID, PRICE_TYPE, BID_RATE, OFFER_RATE, LOWER_BOUND_AMOUNT, UPPER_BOUND_AMOUNT, LAST_TIER_FLAG, SEQ'
    ,'AVANTRADE.MST_LIEN_PRICE_TIERS'
    ,'PRICE_TIER_ID, PRICE_ID, PRICE_TYPE, BID_RATE, OFFER_RATE, LOWER_BOUND_AMOUNT, UPPER_BOUND_AMOUNT, LAST_TIER_FLAG, SEQ'
    ,start_date,'');
END ava_MST_LIEN_PRICE_TIERS;

PROCEDURE ava_MST_LIEN_PRICE_STRUCTURES(start_date TIMESTAMP) AS
BEGIN
process_COMPARE_TABLE(
    'MST_LIEN_PRICE_STRUCTURES@DBLINK_AVANTRADE'
    ,'PRICE_ID, PRODUCT_ID, PRICE_DATE, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, LAST_APPROVED_BY, LAST_APPROVED_DATE, EFFECTIVE_DATE_FROM'
    ,'AVANTRADE.MST_LIEN_PRICE_STRUCTURES'
    ,'PRICE_ID, PRODUCT_ID, PRICE_DATE, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, LAST_APPROVED_BY, LAST_APPROVED_DATE, EFFECTIVE_DATE_FROM'
    ,start_date,'');
END ava_MST_LIEN_PRICE_STRUCTURES;


PROCEDURE ava_TRX_LIEN_TRANSACTION (start_date TIMESTAMP) AS
    v_string_1  VARCHAR2(32767):='TEMP_VIEW_TRX_LIEN_TRANSACTION';
    v_table_temp  VARCHAR2(32767);
    v_table_Insert  VARCHAR2(32767);
  BEGIN
    drop_table(v_string_1) ;
    v_table_temp:='create table '|| v_string_1 || ' as select ' ||
   'TRX_ID, TRX_NO, DEBITOR_CIN, DEBITOR_NAME, TRX_TYPE_GROUP, TRX_TYPE, TRX_BRANCH_ID, TRX_DATE, CREDIT_TYPE,TOTAL_COLLATERAL_CURRENCY, TOTAL_COLLATERAL, PLAFOND_CURRENCY, PLAFOND_AMOUNT, PLAFOND_AMOUNT_IDR, PLAFOND_EXCHANGE_RATE, TENOR_DATE, SECURE_COLLATERAL,EMAIL, ILS_COMMITMENT_NO, RELEASE_TYPE, FORCE_SELL_TYPE, FORCE_SELL_DATE, LIEN_FORCE_SELL_AMOUNT, REMARK, TRX_STATUS,ADD_INFO_1, ADD_INFO_2, DELETE_STATUS, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, LAST_APPROVED_BY, LAST_APPROVED_DATE, LAST_VERSION_DATE ' ||
    'FROM AVANTRADE.TRX_LIEN_TRANSACTIONS WHERE 1=2';
    EXECUTE IMMEDIATE v_table_temp;  
    
    v_table_Insert:= 'INSERT INTO STAGING.'|| v_string_1 ||' SELECT DISTINCT a.HDR_ID TRX_ID, a.LIEN_ID TRX_NO, cus.CIF_BANK DEBITOR_CIN,  AVANTRADE.F_GET_CUSTOMER_FULL_NAME(cus.CUSTOMER_TYPE, cus.COMPANY_NAME, cus.FIRST_NAME, cus.MIDDLE_NAME, cus.LAST_NAME) DEBITOR_NAME,
    CASE WHEN a.TRANSACTION_TYPE = ''NEW'' THEN 1 -- trx type group new
          WHEN a.TRANSACTION_TYPE = ''EDIT_INF'' THEN 2 -- trx type group edit/release
          WHEN a.TRANSACTION_TYPE = ''RELEASE_TRANSACTION'' AND c.LIEN_STATUS = 2 THEN 2 -- trx type group edit/release
          WHEN a.TRANSACTION_TYPE = ''RELEASE_TRANSACTION'' AND c.LIEN_STATUS = 3 THEN 3 -- trx type group force sell
          ELSE 0 END TRX_TYPE_GROUP,
    CASE WHEN a.TRANSACTION_TYPE = ''NEW'' THEN 10 -- trx type new
          WHEN a.TRANSACTION_TYPE = ''EDIT_INF'' THEN 20 -- trx type edit
          WHEN a.TRANSACTION_TYPE = ''RELEASE_TRANSACTION'' AND c.LIEN_STATUS = 2 THEN 22 -- set release to all
          WHEN a.TRANSACTION_TYPE = ''RELEASE_TRANSACTION'' AND c.LIEN_STATUS = 3 THEN 31 -- set force sell to all
          ELSE 0 END TRX_TYPE,
          a.BRANCH_ID TRX_BRANCH_ID,
          a.TRANSACTION_DATE TRX_DATE,
          b."TYPE" CREDIT_TYPE,
          -- TOTAL_COLLATERAL_CURRENCY,TOTAL_COLLATERAL, PLAFOND_CURRENCY, PLAFOND_AMOUNT, PLAFOND_AMOUNT_IDR,PLAFOND_EXCHANGE_RATE          
          NVL(g.Collateral_currency,''IDR'') TOTAL_COLLATERAL_CURRENCY,NVL(g.Amount,0) TOTAL_COLLATERAL,
          NVL(d.loan_plafond_currency,''IDR'') PLAFOND_CURRENCY, d.loan_plafond PLAFOND_AMOUNT,  (d.loan_plafond * 1) PLAFOND_AMOUNT_IDR,
          --NVL(h.CURRENCY_UNIT,1) PLAFOND_EXCHANGE_RATE,
          1 PLAFOND_EXCHANGE_RATE,
          ADD_MONTHS(a.TRANSACTION_DATE, a.TENOR) TENOR_DATE, -- convert tenor to date
          a.SECURE_COLLATERAL_ID SECURE_COLLATERAL,
          a.ACC_OFFICER_EMAIL_ADDR EMAIL,
          d.REMARK ILS_COMMITMENT_NO,
          -- RELEASE_TYPE, FORCE_SELL_TYPE, FORCE_SELL_DATE, LIEN_FORCE_SELL_AMOUNT, REMARK
          CASE WHEN
            a.TRANSACTION_TYPE = ''RELEASE_TRANSACTION'' AND c.LIEN_STATUS = 2 THEN 1 ELSE NULL END RELEASE_TYPE, -- set release type to all
          CASE WHEN
            a.TRANSACTION_TYPE = ''RELEASE_TRANSACTION'' AND c.LIEN_STATUS = 3 THEN 1 ELSE NULL END FORCE_SELL_TYPE, -- set force sell type to all
          e.RELEASED_DATE FORCE_SELL_DATE,
          NVL(f.RELEASED_LIEN_FACE_VALUE, 0) LIEN_FORCE_SELL_AMOUNT,
          f.REMARK,
          a.TRANSACTION_STATUS TRX_STATUS,         
          NULL ADD_INFO_1, NULL ADD_INFO_2,
          0 DELETE_STATUS,
          a.CREATED_BY, a.CREATED_DATE, NVL(a.LAST_UPDATED_BY, a.CREATED_BY) LAST_UPDATED_BY, NVL(a.LAST_UPDATED_DATE, a.CREATED_DATE) LAST_UPDATED_DATE, a.LAST_APPROVED_BY, a.LAST_APPROVED_DATE, NVL(a.LAST_UPDATED_DATE, a.CREATED_DATE) LAST_VERSION_DATE
    
    FROM TRX_FI_LIEN_INFORMATION_HEADER@DBLINK_AVANTRADE a
    INNER JOIN TRX_FI_LIEN_KREDIT_UMUM@DBLINK_AVANTRADE b ON a.HDR_ID = b.HDR_ID
    INNER JOIN TRX_FI_LIEN_STATUS@DBLINK_AVANTRADE c ON a.LIEN_ID = c.LIEN_ID
    INNER JOIN MST_CUSTOMERS@DBLINK_AVANTRADE cus ON a.CUSTOMER_ID = cus.CUSTOMER_ID
    LEFT JOIN TRX_FI_LIEN_INFORMATION_DETAIL@DBLINK_AVANTRADE d ON a.HDR_ID = d.HDR_ID
    LEFT JOIN TRX_FI_LIEN_RELEASED_HEADER@DBLINK_AVANTRADE e ON a.HDR_ID = e.HDR_ID
    LEFT JOIN TRX_FI_LIEN_RELEASED_DETAIL@DBLINK_AVANTRADE f ON e.RELEASED_HEADER_ID = f.RELEASED_HEADER_ID
    LEFT JOIN (select HDR_ID,Collateral_currency,max(Amount)Amount from trx_fi_lien_collateral@DBLINK_AVANTRADE WHERE Collateral_currency=''IDR'' group by HDR_ID,Collateral_currency) G on g.HDR_ID=a.HDR_ID 
    LEFT JOIN MST_EXCHANGE_RATES@DBLINK_AVANTRADE h on NVL(h.currency,''IDR'')=NVL(g.Collateral_currency,''IDR'') 
    AND h.EXCHANGE_RATE_DATE=TRUNC(a.TRANSACTION_DATE) WHERE
    a.TRANSACTION_STATUS = ''APP''
          AND a.CREATED_DATE = (SELECT MAX(CREATED_DATE) FROM TRX_FI_LIEN_INFORMATION_HEADER@DBLINK_AVANTRADE WHERE LIEN_ID = a.LIEN_ID AND a.TRANSACTION_STATUS = ''APP'')
          --AND c.LIEN_STATUS IN (-1,1)
          AND a.LIEN_ID LIKE ''14-%''';
    
    EXECUTE IMMEDIATE v_table_Insert;  
    process_COMPARE_TABLE(
    'STAGING.TEMP_VIEW_TRX_LIEN_TRANSACTION'
    ,'TRX_ID, TRX_NO, DEBITOR_CIN, DEBITOR_NAME, TRX_TYPE_GROUP, TRX_TYPE, TRX_BRANCH_ID, TRX_DATE, CREDIT_TYPE,TOTAL_COLLATERAL_CURRENCY, TOTAL_COLLATERAL, PLAFOND_CURRENCY, PLAFOND_AMOUNT, PLAFOND_AMOUNT_IDR, PLAFOND_EXCHANGE_RATE, TENOR_DATE, SECURE_COLLATERAL,EMAIL, ILS_COMMITMENT_NO, RELEASE_TYPE, FORCE_SELL_TYPE, FORCE_SELL_DATE, LIEN_FORCE_SELL_AMOUNT, REMARK, TRX_STATUS,ADD_INFO_1, ADD_INFO_2, DELETE_STATUS, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, LAST_APPROVED_BY, LAST_APPROVED_DATE, LAST_VERSION_DATE'
    ,'AVANTRADE.TRX_LIEN_TRANSACTIONS'
    ,'TRX_ID, TRX_NO, DEBITOR_CIN, DEBITOR_NAME, TRX_TYPE_GROUP, TRX_TYPE, TRX_BRANCH_ID, TRX_DATE, CREDIT_TYPE,TOTAL_COLLATERAL_CURRENCY, TOTAL_COLLATERAL, PLAFOND_CURRENCY, PLAFOND_AMOUNT, PLAFOND_AMOUNT_IDR, PLAFOND_EXCHANGE_RATE, TENOR_DATE, SECURE_COLLATERAL,EMAIL, ILS_COMMITMENT_NO, RELEASE_TYPE, FORCE_SELL_TYPE, FORCE_SELL_DATE, LIEN_FORCE_SELL_AMOUNT, REMARK, TRX_STATUS,ADD_INFO_1, ADD_INFO_2, DELETE_STATUS, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, LAST_APPROVED_BY, LAST_APPROVED_DATE, LAST_VERSION_DATE'
    ,start_date,'');
END ava_TRX_LIEN_TRANSACTION;

PROCEDURE ava_TRX_LIEN_PRODUCTS (start_date TIMESTAMP) AS
  v_string_1  VARCHAR2(32767):='TEMP_VIEW_TRX_LIEN_PRODUCTS';
    v_table_temp  VARCHAR2(32767);
    v_table_Insert  VARCHAR2(32767);
  BEGIN
    drop_table(v_string_1) ;
    v_table_temp:='create table '|| v_string_1 || ' as select ' ||
   'LIEN_PRODUCT_ID, TRX_ID, CUSTOMER_ID, PRODUCT_ID, AVAILABLE_FACE_VALUE, AMOUNT_BALANCE, COLLATERAL_AMOUNT, EXCHANGE_RATE, RELEASE_AMOUNT, FORCE_SELL_AMOUNT, REMARK, SEQ, DELETE_STATUS, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, TAX_AMNESTY_FLAG ' ||
    'FROM AVANTRADE.TRX_LIEN_PRODUCTS WHERE 1=2';
    EXECUTE IMMEDIATE v_table_temp;  
    v_table_Insert:= 'INSERT INTO STAGING.' || v_string_1 || ' (LIEN_PRODUCT_ID, TRX_ID, CUSTOMER_ID, PRODUCT_ID, AVAILABLE_FACE_VALUE, AMOUNT_BALANCE, COLLATERAL_AMOUNT, EXCHANGE_RATE, RELEASE_AMOUNT, FORCE_SELL_AMOUNT, REMARK, SEQ, DELETE_STATUS, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, TAX_AMNESTY_FLAG) ' ||
    'SELECT a.LIEN_DETAIL_ID LIEN_PRODUCT_ID, b.HDR_ID TRX_ID, b.CUSTOMER_ID CUSTOMER_ID, a.PRODUCT_ID, a.AVAILABLE_FACE_VALUE, NVL(a.AMOUNT_BALANCE,0) AMOUNT_BALANCE, a.LIEN_FACE_VALUE COLLATERAL_AMOUNT, 1 EXCHANGE_RATE,  ' ||
    'CASE WHEN ' ||
      'b.TRANSACTION_TYPE = ''RELEASE_TRANSACTION'' AND c.LIEN_STATUS = 2 THEN NVL(f.RELEASED_LIEN_FACE_VALUE, 0) ELSE 0 END RELEASE_AMOUNT, ' ||
    'CASE WHEN ' ||
      'b.TRANSACTION_TYPE = ''RELEASE_TRANSACTION'' AND c.LIEN_STATUS = 3 THEN NVL(f.RELEASED_LIEN_FACE_VALUE, 0) ELSE 0 END FORCE_SELL_AMOUNT, ' ||
    'a.REMARK, 1 SEQ, 0 DELETE_STATUS, b.CREATED_BY, b.CREATED_DATE, NVL(b.LAST_UPDATED_BY, b.CREATED_BY) LAST_UPDATED_BY, NVL(b.LAST_UPDATED_DATE,b.CREATED_DATE) LAST_UPDATED_DATE, a.TAX_AMNESTY_FLAG ' ||
    'FROM TRX_FI_LIEN_INFORMATION_DETAIL@DBLINK_AVANTRADE a ' ||
    'INNER JOIN TRX_FI_LIEN_INFORMATION_HEADER@DBLINK_AVANTRADE b ON a.HDR_ID = b.HDR_ID ' ||
    'INNER JOIN TRX_FI_LIEN_STATUS@DBLINK_AVANTRADE c ON b.LIEN_ID = c.LIEN_ID ' ||
    'LEFT JOIN TRX_FI_LIEN_RELEASED_HEADER@DBLINK_AVANTRADE e ON a.HDR_ID = e.HDR_ID ' ||
    'LEFT JOIN TRX_FI_LIEN_RELEASED_DETAIL@DBLINK_AVANTRADE f ON e.RELEASED_HEADER_ID = f.RELEASED_HEADER_ID ' ||
    'WHERE EXISTS (SELECT 1 FROM AVANTRADE.TRX_LIEN_TRANSACTIONS c where c.TRX_ID = a.HDR_ID) ';
    EXECUTE IMMEDIATE v_table_Insert; 
    
    process_COMPARE_TABLE(
    'STAGING.TEMP_VIEW_TRX_LIEN_PRODUCTS'
    ,'LIEN_PRODUCT_ID, TRX_ID, CUSTOMER_ID, PRODUCT_ID, AVAILABLE_FACE_VALUE, AMOUNT_BALANCE, COLLATERAL_AMOUNT, EXCHANGE_RATE, RELEASE_AMOUNT, FORCE_SELL_AMOUNT, REMARK, SEQ, DELETE_STATUS, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, TAX_AMNESTY_FLAG'
    ,'AVANTRADE.TRX_LIEN_PRODUCTS'
    ,'LIEN_PRODUCT_ID, TRX_ID, CUSTOMER_ID, PRODUCT_ID, AVAILABLE_FACE_VALUE, AMOUNT_BALANCE, COLLATERAL_AMOUNT, EXCHANGE_RATE, RELEASE_AMOUNT, FORCE_SELL_AMOUNT, REMARK, SEQ, DELETE_STATUS, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATED_DATE, TAX_AMNESTY_FLAG'
    ,start_date,'');
END ava_TRX_LIEN_PRODUCTS;

END PCKG_MIG_COMPARE_LIEN;